### ISSUE TITLE
Sprint 1.1 (2017-10-17)

### ISSUE THREAD

**Issue by bike-bill** [bike-bill/cycle#6]
# Sprint Goal

_Increase your chances of getting to where you want to be by defining where you want to be!_

_A good Sprint Goal should be specific and measurable, helping to align the team to a common purpose. For example:_

- Implement iOS prototype screens to test user interactions
- Allow creation of multiple pipelines on the ZenHub board

# Sprint Deliverables

_What concrete deliverables do you have for the sprint? Using GitHub markdown, we can easily list and track their completion._

- [ ]  #1 - Include static web resources
- [ ]  #2 - Add Spring classics results
- [ ]  #3 - Enable all fixtures

# Sprint Metrics and Targets

_How long will the sprint run for and what are our criteria for success? Including this information here makes it really easy to look back for future reference._

The sprint will run for one week and be considered a success based on:

- Information gained from User Feedback that will help us define the next iteration of the product
- Ability to add multiple pipelines to a ZenHub board in production with no downtime or negative impact to ZenHub users
